"""
_integrations/connectors/{{TOOL_NAME}}.py — stub generated by /tools-setup.

Purpose: push / pull data between the Marketing Cockpit and {{TOOL_NAME}}
({{TOOL_CATEGORY}} category).

This is a stub. You (or your developer) implement the two entry points below
before the first real sync or push.

## Contract

A connector exposes a minimum surface:

    - `dry_run(content: dict) -> dict`
        Given a parsed content file (frontmatter + body), return the payload
        that would be sent to {{TOOL_NAME}}. Must not make any HTTP call.
        Called by `scripts/dry-run-push.py`.

    - `push(content: dict, *, confirm: bool = True) -> dict`
        Perform the actual push. Raises on failure. If `confirm=True`, echo
        the target resource (id, URL) for human verification before the call.
        Must honor the `DRY_RUN=true` env var and short-circuit to dry_run().

    - (pull-capable connectors) `list_items() -> Iterable[dict]`
        Yield items pulled from {{TOOL_NAME}} (e.g. calendar entries, posts).

## Environment variables

Expected in `.env` (do not commit real values):

{{ENV_KEYS_BLOCK}}

Check presence at import time; do not read values unnecessarily.

## Security

- Never print API keys back to the user or into logs.
- Validate all input. {{TOOL_NAME}} APIs may interpret certain characters.
- Respect rate limits. See the runbook for the recommended sleep pattern.
- For push connectors: default to creating as DRAFT. Never send / publish
  without explicit user confirmation in the same session.

## TODO checklist

- [ ] Wire the API client (official SDK if it exists; plain `requests` otherwise)
- [ ] Implement `dry_run()` — payload construction, no I/O
- [ ] Implement `push()` — real call with retry and clean errors
- [ ] (if applicable) Implement `list_items()` for ingestion
- [ ] Add the connector to `_integrations/connectors/__init__.py`
- [ ] Update `docs/tools.json` to flip `connector_status` from "stub" to "ready"
- [ ] Regenerate the README tool-status board via `/tools-setup`

"""
from __future__ import annotations

import logging
import os
from typing import Any

logger = logging.getLogger("connectors.{{TOOL_NAME}}")

# -------------------------------------------------------------------------
# Required env keys. Presence check at import time — do not read values.
# -------------------------------------------------------------------------
REQUIRED_ENV_KEYS: list[str] = [
{{REQUIRED_ENV_KEYS_LIST}}
]

for _k in REQUIRED_ENV_KEYS:
    if not os.environ.get(_k):
        logger.warning("{{TOOL_NAME}} connector: env var %s is not set.", _k)


# -------------------------------------------------------------------------
# Contract
# -------------------------------------------------------------------------
def dry_run(content: dict[str, Any]) -> dict[str, Any]:
    """
    Return the payload that would be sent. No HTTP call.

    `content` shape (produced by scripts/dry-run-push.py):
        {
          "frontmatter": { ... yaml frontmatter as dict ... },
          "body":        "...markdown body...",
          "path":        "path/to/source/file.md"
        }
    """
    raise NotImplementedError("Implement dry_run() for {{TOOL_NAME}}.")


def push(content: dict[str, Any], *, confirm: bool = True) -> dict[str, Any]:
    """
    Perform the real push. Return the created resource (id, URL) on success.

    If `DRY_RUN=true` in the environment, short-circuit to dry_run() and
    return its output — this is a safety net for accidental pushes.
    """
    if os.environ.get("DRY_RUN", "").lower() == "true":
        logger.info("DRY_RUN=true → short-circuiting to dry_run().")
        return dry_run(content)

    raise NotImplementedError("Implement push() for {{TOOL_NAME}}.")


# -------------------------------------------------------------------------
# Optional: pull entry point.
# Implement if {{TOOL_NAME}} can be a source of content to pull locally.
# -------------------------------------------------------------------------
def list_items():
    """Yield dicts shaped like `{"id": str, "title": str, "body": str, "metadata": {...}}`."""
    raise NotImplementedError("Implement list_items() for {{TOOL_NAME}} if it's an ingestion source.")
